### ISSUE TITLE
pause stream instead of listening for unblock event

### ISSUE THREAD

**Issue by fiws** [restore-commerce/gss-client#1]
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at GraphStorage.EventEmitter.addListener (events.js:179:15)
    at GraphStorage.EventEmitter.once (events.js:204:8)
    at GraphStorage._lazyImport (/node_modules/invend-gss/index.js:96:10)
    at Stream.<anonymous> (/node_modules/invend-gss/index.js:69:14)
    at Stream.EventEmitter.emit (events.js:107:17)
[...]
```

**Comment by vanthome** [comment]
not relevant with 0.2.0
